Controllers/EsquemasProteccionController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EsquemasSecundarios.Models;
using System.Data.SqlClient;
using System.Web.Configuration;
using System;

namespace EsquemasSecundarios.Controllers
{
    [TienePermiso(Servicio: 9)]// Servicio: Gestionar Esquemas de Protección
    public class EsquemasProteccionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        #region CRUD

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.EsquemasProteccion.OrderByDescending(c => c.id_Esquema).ToList());
        }

        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EsquemaProteccion esquemaProteccion = db.EsquemasProteccion.Find(id);
            if (esquemaProteccion == null)
            {
                return HttpNotFound();
            }

            ViewBag.Interruptores = (
                from ed in db.Esquema_Desconectivo
                where ed.esquema.Equals(esquemaProteccion.id_Esquema)
                select ed.desconectivo
                ).ToList();

            ViewBag.TC = (
                from e in db.Esquema_TC
                where e.esquema.Equals(esquemaProteccion.id_Esquema)
                select e.TC
                ).ToList();

            ViewBag.TP = (
                from e in db.Esquema_TP
                where e.esquema.Equals(esquemaProteccion.id_Esquema)
                select e.TP
                ).ToList();

            ViewBag.Relevadores = (
                from e in db.Esquema_Rele
                where e.esquema.Equals(esquemaProteccion.id_Esquema)
                select e.rele
                ).ToList();

            return View(esquemaProteccion);
        }

        public ActionResult Create()
        {
            Inicializar();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "id_Esquema,Nombre,Subestacion,Tipo_Equipo_Primario,Elemento_Electrico,Clase")] EsquemaProteccion esquemaProteccion,
            string[] Interruptores, string[] TC, string[] TP, string[] Relevadores, string RelevadorFunc, int[] Funciones
        )
        {
            var usuario = System.Web.HttpContext.Current.User?.Identity?.Name ?? null;
            string nombre_usuario = System.Web.HttpContext.Current.User.Identity.Name;
            var usuario_logueado = db.Personal.FirstOrDefault(c => c.Nombre == nombre_usuario);
            short EAdmin = usuario_logueado.id_EAdministrativa;

            if (ModelState.IsValid)
            {
                esquemaProteccion.Id_EAdministrativa = EAdmin;
                esquemaProteccion.Id_NumAccion = GetNumAccion("I", "ESE", 0);
                EsquemaProteccion ep = db.EsquemasProteccion.Add(esquemaProteccion);
                db.Entry(ep).State = EntityState.Added;

                if (Interruptores != null)
                {
                    foreach (var item in Interruptores)
                    {
                        Esquema_Desconectivo e = new Esquema_Desconectivo();
                        e.desconectivo = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_Desconectivo.Add(e);
                    }
                }

                if (TC != null)
                {
                    foreach (var item in TC)
                    {
                        Esquema_TC e = new Esquema_TC();
                        e.TC = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_TC.Add(e);
                    }
                }

                if (TP != null)
                {
                    foreach (var item in TP)
                    {
                        Esquema_TP e = new Esquema_TP();
                        e.TP = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_TP.Add(e);
                    }
                }

                if (Relevadores != null)
                {
                    foreach (var item in Relevadores)
                    {
                        Esquema_Relevador e = new Esquema_Relevador();
                        e.rele = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_Rele.Add(e);
                    }
                }

                if (Funciones != null)
                {
                    var PlantillaId = (
                        from p in db.Plantillas
                        join r in db.Relevadores on p.id_Plantilla equals r.id_Plantilla
                        where r.Nro_Serie.Contains(RelevadorFunc)
                        select p.id_Plantilla
                    ).ToList();

                    foreach (var item in Funciones)
                    {
                        Plantilla_Funcion pf = new Plantilla_Funcion();
                        pf.id_Funcion = item;
                        pf.id_Plantilla = PlantillaId[0];
                        db.Plantilla_Funcion.Add(pf);
                    }
                }

                db.SaveChanges();
                return RedirectToAction("Details", new { id = esquemaProteccion.id_Esquema });
            }
            Inicializar(esquemaProteccion);
            return View(esquemaProteccion);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EsquemaProteccion esquemaProteccion = db.EsquemasProteccion.Find(id);
            if (esquemaProteccion == null)
            {
                return HttpNotFound();
            }
            Inicializar(esquemaProteccion);
            ViewBag.Titulo = "Interruptores / Desconectivos";
            return View(esquemaProteccion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_Esquema,Nombre,Subestacion,Tipo_Equipo_Primario,Elemento_Electrico,Clase")] EsquemaProteccion esquemaProteccion,
            string[] Interruptores, string[] TC, string[] TP, string[] Relevadores, string RelevadorFunc, int[] Funciones)
        {
            var usuario = System.Web.HttpContext.Current.User?.Identity?.Name ?? null;
            string nombre_usuario = System.Web.HttpContext.Current.User.Identity.Name;
            var usuario_logueado = db.Personal.FirstOrDefault(c => c.Nombre == nombre_usuario);
            short EAdmin = usuario_logueado.id_EAdministrativa;

            if (ModelState.IsValid)
            {
                db.Entry(esquemaProteccion).State = EntityState.Modified;

                if (Interruptores != null)
                {
                    if (db.Esquema_Desconectivo.Where(c => c.esquema == esquemaProteccion.id_Esquema).Select(c => c.esquema).ToList() != null)
                    {
                        db.Esquema_Desconectivo.RemoveRange(db.Esquema_Desconectivo.Where(c => c.esquema == esquemaProteccion.id_Esquema));
                    }
                    
                    foreach (var item in Interruptores)
                    {
                        Esquema_Desconectivo e = new Esquema_Desconectivo();
                        e.desconectivo = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_Desconectivo.Add(e);
                    }
                }

                if (TC != null)
                {
                    if (db.Esquema_TC.Where(c => c.esquema == esquemaProteccion.id_Esquema).Select(c => c.esquema).ToList() != null)
                    {
                        db.Esquema_TC.RemoveRange(db.Esquema_TC.Where(c => c.esquema == esquemaProteccion.id_Esquema));
                    }
                    
                    foreach (var item in TC)
                    {
                        Esquema_TC e = new Esquema_TC();
                        e.TC = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_TC.Add(e);
                    }
                }

                if (TP != null)
                {
                    if (db.Esquema_TP.Where(c => c.esquema == esquemaProteccion.id_Esquema).Select(c => c.esquema).ToList() != null)
                    {
                        db.Esquema_TP.RemoveRange(db.Esquema_TP.Where(c => c.esquema == esquemaProteccion.id_Esquema));
                    }
                    
                    foreach (var item in TP)
                    {
                        Esquema_TP e = new Esquema_TP();
                        e.TP = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_TP.Add(e);
                    }
                }

                if (Relevadores != null)
                {
                    if (db.Esquema_Rele.Where(c => c.esquema == esquemaProteccion.id_Esquema).Select(c => c.esquema).ToList() != null)
                    {
                        db.Esquema_Rele.RemoveRange(db.Esquema_Rele.Where(c => c.esquema == esquemaProteccion.id_Esquema));
                    }
                    
                    foreach (var item in Relevadores)
                    {
                        Esquema_Relevador e = new Esquema_Relevador();
                        e.rele = item;
                        e.esquema = esquemaProteccion.id_Esquema;
                        db.Esquema_Rele.Add(e);
                    }
                }

                if (Funciones != null)
                {
                    var PlantillaId = (
                        from p in db.Plantillas

Views/EsquemasProteccion/Delete.cshtml
@model EsquemasSecundarios.Models.EsquemaProteccion
@{ 
    ViewBag.Title = "Esquemas de protección";
    ViewBag.PTitle = "Eliminar esquema";
}
<!-- content starts here -->
<h3 class="alert alert-warning">&iexcl;Advertencia! - Esta acción es irreversible.</h3>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>@ViewBag.PTitle</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table">
                    <tr>
                        <th>Nombre del esquema</th>
                        <td>@Html.DisplayFor(model => model.Nombre)</td>
                    </tr>
                    <tr>
                        <th>Tipo de instalación</th>
                        <td>@Html.DisplayFor(model => model.Subestacion)</td>
                    </tr>
                    <tr>
                        <th>Tipo de equipo primario</th>
                        <td>@Html.DisplayFor(model => model.Tipo_Equipo_Primario)</td>
                    </tr>
                    <tr>
                        <th>Nombre del elemento eléctrico</th>
                        <td>@Html.DisplayFor(model => model.Elemento_Electrico)</td>
                    </tr>
                </table>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <button type="submit" class="btn btn-danger"><i class="fa fa-eraser"></i> Eliminar</button>
                        <a class="btn btn-default" href="@Url.Action("Index","EsquemasProteccion")">Listado</a>
                    </div>
                }
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

Views/EsquemasProteccion/Details.cshtml
@model EsquemasSecundarios.Models.EsquemaProteccion

@{
    ViewBag.Title = "Esquemas de protección";
    ViewBag.PTitle = "Detalles del esquema";
}
<!-- content starts here -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>@ViewBag.PTitle</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- content starts here -->
                <div class="row clearfix">
                    <!-- price element -->
                    <div class="col-md-12">
                        <div class="pricing">
                            <div class="x_content">
                                <div class="">
                                    <div class="pricing_features">
                                        <h3>Datos generales del esquema</h3>
                                        <table class="table">
                                            <tr>
                                                <th>Nombre del esquema</th>
                                                <td>@Html.DisplayFor(model => model.Nombre)</td>
                                            </tr>
                                            <tr>
                                                <th>Tipo de instalación</th>
                                                <td>@Html.DisplayFor(model => model.Subestacion)</td>
                                            </tr>
                                            <tr>
                                                <th>Tipo de equipo primario</th>
                                                <td>@Html.DisplayFor(model => model.Tipo_Equipo_Primario)</td>
                                            </tr>
                                            <tr>
                                                <th>Nombre del elemento eléctrico</th>
                                                <td>@Html.DisplayFor(model => model.Elemento_Electrico)</td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                                <hr />
                                <p>
                                    <a class="btn btn-success" href="@Url.Action("Create","EsquemasProteccion")"><i class="fa fa-plus"></i> Crear</a>
                                    <a class="btn btn-info" href="@Url.Action("Edit","EsquemasProteccion", new { id = Model.id_Esquema })"><i class="fa fa-edit"></i> Editar</a>
                                    <a class="btn btn-default" href="@Url.Action("Index","EsquemasProteccion")"><i class="fa fa-list"></i> Listado</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- price element -->
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <h3>Elementos asociados al esquema</h3>
                                <div class="col-md-3">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Interruptores</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in ViewBag.Interruptores)
                                            {
                                                <tr>
                                                    <td>@item</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-3">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>TC</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in ViewBag.TC)
                                            {
                                                <tr>
                                                    <td>@item</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-3">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>TP</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in ViewBag.TP)
                                            {
                                                <tr>
                                                    <td>@item</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-3">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Relevadores</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in ViewBag.Relevadores)
                                            {
                                                <tr>
                                                    <td>@item</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

Views/EsquemasProteccion/Index.cshtml
@model IEnumerable<EsquemasSecundarios.Models.EsquemaProteccion>

@{
    ViewBag.Title = "Esquemas de protección";
    ViewBag.PTitle = "Listado de esquemas";
}
<!-- content starts here -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>@ViewBag.PTitle</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- content starts here -->
                <div class="row">
                    <div class="col-md-12">
                        <table id="datatable" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Instalación</th>
                                    <th>Clase de Esquema</th>
                                    <th>Tipo Equipo Primario</th>
                                    <th>Elemento Eléctrico</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Subestacion)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Clase)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Tipo_Equipo_Primario)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Elemento_Electrico)</td>
                                        <td>
                                            <a href="@Url.Action("Details","EsquemasProteccion", new { id = item.id_Esquema } )" class="btn btn-info btn-xs" title="Detalles"><i class="fa fa-eye"></i>  </a>
                                            <a href="@Url.Action("Edit","EsquemasProteccion", new { id = item.id_Esquema } )" class="btn btn-warning btn-xs" title="Editar"><i class="fa fa-pencil"></i>  </a>
                                            <a href="@Url.Action("Delete","EsquemasProteccion", new { id = item.id_Esquema } )" class="btn btn-danger btn-xs" title="Eliminar"><i class="fa fa-trash-o"></i>  </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-12">
                        <a href="@Url.Action("Create","EsquemasProteccion")" class="btn btn-info"><i class="fa fa-plus"></i> Nuevo</a>
                    </div>
                </div>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>


@section styles {
    @Styles.Render("~/Style/DataTables")
}

@section script {
    @Scripts.Render("~/Script/DataTables")
}

Views/EsquemasProteccion/_VPElementoElectrico.cshtml
@if (!ViewBag.Especificar)
{
    @Html.DropDownList("Elemento_Electrico", null, "", htmlAttributes: new { @class = "select2_single form-control col-md-12", @id = "SelectorElementoElectrico" })
}
else
{
    <input type="text" class="form-control" name="Elemento_Electrico" id="SelectorElementoElectrico" value="Ninguno" placeholder="Inserte el nombre del elemento eléctrico"/>
}

<script>
    $("#SelectorElementoElectrico").change(function () {
        if ($("#TipoEsquema").val() == "Esquema de Protección del Transformador") {
            $("#NombreEsquema").val($("#SelectorTipoEsquema").val() + " " + $("#SelectorElementoElectrico").val());
        }
        if ($("#TipoEsquema").val() == "Esquema de Control - Ventilación del Transformador") {
            $("#NombreEsquema").val($("#SelectorTipoEsquema").val() + " " + $("#SelectorElementoElectrico").val());
        }
        if ($("#TipoEsquema").val() == "Esquema de Control - Cambia Taps del Transformador") {
            $("#NombreEsquema").val($("#SelectorTipoEsquema").val() + " " + $("#SelectorElementoElectrico").val());
        }
        if ($("#TipoEsquema").val() == "Esquema de Control - Potenciales de la Barra") {
            $("#NombreEsquema").val($("#SelectorTipoEsquema").val() + " " + $("#SelectorElementoElectrico").val());
        } 
        if ($("#TipoEsquema").val() == "Esquema de Protección – Diferencial de la Barra") {
            $("#NombreEsquema").val($("#SelectorTipoEsquema").val() + " " + $("#SelectorElementoElectrico").val());
        }
        if ($("#TipoEsquema").val() == "Esquema de Protección Especial de la Barra") {
            $("#NombreEsquema").val($("#SelectorTipoEsquema").val() + " " + $("#SelectorElementoElectrico").val());
        }
    })
</script>

Views/EsquemasProteccion/_VPFunciones.cshtml
<h2>Funciones asociadas a este relevador</h2>
<div class="row clearfix">
    <div class="form-group">
        <div class="col-md-12">
            @Html.DropDownList("Funciones", null, "", new { @class = "select2_multiple form-control", multiple = "multiple" })
        </div>
    </div>
</div>

Views/EsquemasProteccion/_VPInstalaciones.cshtml
@if (ViewBag.TipoInstalacion == "Subestacion")
{
    <small>Subestaciones</small>
    @Html.DropDownList("Subestacion", null, "", htmlAttributes: new { @class = "select2_single form-control", @id = "SelectorSubestacion" })
}
@if (ViewBag.TipoInstalacion == "Línea")
{
    <small>Líneas</small>
    @Html.DropDownList("Subestacion", null, "", htmlAttributes: new { @class = "select2_single form-control", @id = "SelectorSubestacion" })
}

<input type="hidden" id="TipoEsquema" value="@ViewBag.TipoEsquema" />

<script>
    $("#SelectorSubestacion").change(function () {
        var codsub = $(this).val();
        CargarTransformadores(codsub);

        var tipoesquema = $("#TipoEsquema").val();
        if (tipoesquema == "Esquema de Protección y Control del Interruptor") {            
            CargarElementosElectricos("Línea", codsub);
            CargarInterruptores(codsub, "Interruptores", false);            
        }
        if (tipoesquema == "Esquema de Protección del Transformador") {
            CargarElementosElectricos("Transformador", codsub);
            CargarInterruptores(codsub, "Interruptores", false);            
        }
        if (tipoesquema == "Esquema de Control - Ventilación del Transformador") {
            CargarElementosElectricos("Transformador", codsub);
        }
        if (tipoesquema == "Esquema de Control - Cambia Taps del Transformador") {
            CargarElementosElectricos("Transformador", codsub);
        }
        if (tipoesquema == "Esquema de Control – del Desconectivo") {
            CargarElementosElectricos("Ninguno", codsub);
            CargarInterruptores(codsub, "Desconectivos", false);
        }
        if (tipoesquema == "Esquema de Control - Potenciales de la Barra") {
            CargarElementosElectricos("Barra", codsub);
        }
        if (tipoesquema == "Esquema de Señalización Central") {
            CargarElementosElectricos("Ninguno", codsub);
        }
        if (tipoesquema == "Esquema de Control – Cargador de Baterías") {
            CargarElementosElectricos("Ninguno", codsub);
        }
        if (tipoesquema == "Esquema de Protección – Diferencial de la Barra") {
            CargarElementosElectricos("Barra", codsub);
            CargarInterruptores(codsub, "Interruptores", false);
        }
        if (tipoesquema == "Esquema de Protección DAF/DAV") {
            CargarElementosElectricos("Ninguno", codsub);
            CargarInterruptores(codsub, "Interruptores", false);
        }
        if (tipoesquema == "Esquema de Control Distribución de Corriente Directa") {
            CargarElementosElectricos("Ninguno", codsub);
        }
        if (tipoesquema == "Esquema de Control Distribución de Corriente Alterna") {
            CargarElementosElectricos("Ninguno", codsub);
        }
        if (tipoesquema == "Esquema de Automática RAS (Reposición Automática del Servicio)") {
            CargarElementosElectricos("Ninguno", codsub);
            CargarInterruptores(codsub, "Interruptores", false);
        }
        if (tipoesquema == "Esquema de Protección Especial de la Barra") {
            CargarElementosElectricos("Barra", codsub);
            CargarInterruptores(codsub, "Interruptores", false);
        }
        if (tipoesquema == "Esquema de Protección Separadora") {
            CargarElementosElectricos("Ninguno", codsub);
        }
        if (tipoesquema == "Esquema de Automática de Líneas") {
            $("#Elemento_Electrico").val(codsub);
            CargarInterruptores(codsub, "Selectivos y Recerradores", true);
        }
    })
</script>

Views/EsquemasProteccion/_VPInterruptores.cshtml
<h2>@ViewBag.Titulo</h2>
<div class="row clearfix">
    <div class="col-md-12">
        <div class="form-group">
            @if (ViewBag.EsMultiple)
            {
                @Html.DropDownList("Interruptores", null, "", htmlAttributes: new { @class = "select2_multiple form-control", @multiple = "multiple", @id = "SelectorInterruptor" })
            }
            else
            {
                @Html.DropDownList("Interruptores", null, "", htmlAttributes: new { @class = "select2_single form-control", @id = "SelectorInterruptor" })
            } 
        </div>
    </div>
</div>

<script>    
    $("#SelectorInterruptor").change(function () {
        if ($("#SelectorTipoEsquema").val() != "" && $("#SelectorInterruptor").val() != "" && ( $("#TipoEsquema").val() == "Esquema de Protección y Control del Interruptor" || $("#TipoEsquema").val() == "Esquema de Control – del Desconectivo"))            
        {
            $("#NombreEsquema").val($("#SelectorTipoEsquema").val() + " " + $("#SelectorInterruptor").val());
        }     
    })
</script>