Models/Plantilla.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EsquemasSecundarios.Models
{
    [Table("ES_Plantilla_Rele")]
    public class Plantilla
    {
        [Key]
        public int id_Plantilla { get; set; }
        public string Modelo { get; set; }
        public int Id_Fabricante { get; set; }

        public List<Relevador> Relevadores { get; set; }
        public List<Plantilla_Funcion> Plantillas_Funciones { get; set; }

        [ForeignKey("Id_Fabricante")]
        public Fabricante Fabricante { get; set; }
        
    }
}

Controllers/PlantillasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EsquemasSecundarios.Models;

namespace EsquemasSecundarios.Controllers
{    
    public class PlantillasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Plantillas
        [AllowAnonymous]
        public ActionResult Index()
        {
            var plantillas = db.Plantillas.Include(p => p.Fabricante);
            return View(plantillas.ToList());
        }

        // GET: Plantillas/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Plantilla plantilla = db.Plantillas.Find(id);

            var fabricante = db.Plantillas.Include(p => p.Fabricante).FirstOrDefault().Fabricante.Nombre;

            if (plantilla == null)
            {
                return HttpNotFound();
            }

            var f =(
                from pl in db.Plantillas
                join pf in db.Plantilla_Funcion on pl.id_Plantilla equals pf.id_Plantilla
                join fun in db.Funciones on pf.id_Funcion equals fun.Id_Esquema
                where pl.id_Plantilla == id
                select fun.Descripcion
                ).ToList();

            ViewBag.Fabricante = fabricante;
            ViewBag.Funciones = f;

            return View(plantilla);
        }

        // GET: Plantillas/Create
        public ActionResult Create()
        {
            ViewBag.Id_Fabricante = new SelectList(db.Fabricantes, "Id_Fabricante", "Nombre");
            ViewBag.Funciones = new SelectList(db.Funciones, "Id_Esquema", "Descripcion");
            return View();
        }

        // POST: Plantillas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_Plantilla,Modelo,Id_Fabricante")] Plantilla plantilla, int[] Funciones)
        {
            if (ModelState.IsValid)
            {
                db.Plantillas.Add(plantilla);
                db.SaveChanges();

                for (int i = 0; i < Funciones.Length; i++)
                {
                    Plantilla_Funcion pf = new Plantilla_Funcion();
                    pf.id_Plantilla = plantilla.id_Plantilla;
                    pf.id_Funcion = Funciones[i];
                    db.Plantilla_Funcion.Add(pf);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            ViewBag.Id_Fabricante = new SelectList(db.Fabricantes, "Id_Fabricante", "Nombre", plantilla.Id_Fabricante);
            ViewBag.Funciones = new SelectList(db.Funciones, "Id_Esquema", "Descripcion");
            return View(plantilla);
        }

        // GET: Plantillas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plantilla plantilla = db.Plantillas.Find(id);
            if (plantilla == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Fabricante = new SelectList(db.Fabricantes, "Id_Fabricante", "Nombre", plantilla.Id_Fabricante);

            var funcIds = (
                from pf in db.Plantilla_Funcion
                where pf.id_Plantilla.Equals(plantilla.id_Plantilla)
                select pf.id_Funcion
            ).ToList();

            var allfunc = db.Funciones.ToList().OrderBy(c => c.Descripcion);

            ViewBag.Funciones = new MultiSelectList(allfunc, "Id_Esquema", "Descripcion", funcIds);

            return View(plantilla);
        }

        // POST: Plantillas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_Plantilla,Modelo,Id_Fabricante")] Plantilla plantilla, int[] Funciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(plantilla).State = EntityState.Modified;
                db.SaveChanges();
                if (Funciones != null )
                {
                    for (int i = 0; i < Funciones.Length; i++)
                    {
                        Plantilla_Funcion pf = new Plantilla_Funcion();
                        pf.id_Plantilla = plantilla.id_Plantilla;
                        pf.id_Funcion = Funciones[i];
                        db.Plantilla_Funcion.Add(pf);
                        db.SaveChanges();
                    }
                }
                

                return RedirectToAction("Index");
            }
            ViewBag.Id_Fabricante = new SelectList(db.Fabricantes, "Id_Fabricante", "Nombre", plantilla.Id_Fabricante);
            return View(plantilla);
        }

        // GET: Plantillas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plantilla plantilla = db.Plantillas.Find(id);
            if (plantilla == null)
            {
                return HttpNotFound();
            }
            return View(plantilla);
        }

        // POST: Plantillas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Plantilla plantilla = db.Plantillas.Find(id);
            db.Plantillas.Remove(plantilla);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Plantillas/Details.cshtml
@model EsquemasSecundarios.Models.Plantilla

@{
    ViewBag.Title = "Plantillas Rele";
    ViewBag.PTitle = "Detalles de la plantilla";
}
<!-- content starts here -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>@ViewBag.PTitle</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- content starts here -->
                <div class="row clearfix">
                    <div class="col-md-12">
                        <table class="table">
                            <tr>
                                <th>Modelo</th>
                                <td>@Html.DisplayFor(model => model.Modelo)</td>
                            </tr>
                            <tr>
                                <th>Fabricante</th>
                                <td>@ViewBag.Fabricante</td>
                            </tr>
                            <tr>
                                <th>Funciones</th>
                                <td>
                                    <ul>
                                        @foreach (var item in ViewBag.Funciones)
                                        {
                                            <li>@item</li>
                                        }
                                    </ul>                                    
                                </td>
                            </tr>                            
                        </table>
                    </div>
                </div>

                <hr />
                <p>
                    <a class="btn btn-default" href="@Url.Action("Index","Plantillas")"><i class="fa fa-list"></i> Listado</a>
                </p>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

Views/Plantillas/Index.cshtml
@model IEnumerable<EsquemasSecundarios.Models.Plantilla>

@{
    ViewBag.Title = "Plantillas de relevadores";
    ViewBag.PTitle = "Listado";
}
<!-- content starts here -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>@ViewBag.PTitle</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- content starts here -->
                <div class="row">
                    <div class="col-md-12">

                        <table id="datatable" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Modelo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Fabricante)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Modelo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Fabricante.Nombre)
                                        </td>
                                        <td style="width: 40px;">
                                            <a href="@Url.Action("Details","Plantillas", new { id = item.id_Plantilla } )" class="btn btn-info btn-xs" title="Detalles"><i class="fa fa-eye"></i>  </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

@section styles {
    @Styles.Render("~/Style/DataTables")
}

@section script {
    @Scripts.Render("~/Script/DataTables")
}