Models/Averias.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EsquemasSecundarios.Models
{
    [Table("ES_Averias")]
    public class Averias
    {
        [Key]
        public int IdAveria { get; set; }

        [Required(ErrorMessage = "Debe introducir el campo: {0}")]
        [Display(Name = "Fecha del Reporte"), DisplayFormat(DataFormatString = "{0:yyy-MM-dd h:mm tt}")]
        public DateTime FechaReporte { get; set; }

        [Display(Name = "Fecha de Atención"), DisplayFormat(DataFormatString = "{0:yyy-MM-dd h:mm tt}")]
        public DateTime FechaAtencion { get; set; }

        [Display(Name = "Atendido Por")]
        public string PersonaQueAtendio { get; set; }

        [Display(Name = "Datos Reportados")]
        public string DatosReportados { get; set; }

        [Display(Name = "Análisis")]
        public string Analisis { get; set; }

        public string Conclusiones { get; set; }

        public string Recomendaciones { get; set; }

        [Display(Name = "Elaborado Por")]
        public string ElaboradoPor { get; set; }

        [Display(Name = "Revisado Por")]
        public string RevisadoPor { get; set; }

        [Display(Name = "Aprobado Por")]
        public string AprobadoPor { get; set; }

        [Display(Name = "Subestación"), Required(ErrorMessage = "Debe introducir el campo: {0}")]
        public string CodSubestacion { get; set; }

        [Display(Name = "Esquema"),Required(ErrorMessage = "Debe introducir el campo: {0}")]
        public int IdEsquema { get; set; }

        public short? Id_EAdministrativa { get; set; }

        public int? Id_NumAccion { get; set; }


        //Propiedades Virtuales Referencias a otras clases
        [ForeignKey("CodSubestacion"),Display(Name = "Subestación")]
        public Subestacion Subestacion { get; set; }

        [ForeignKey("IdEsquema")]
        public EsquemaProteccion Esquema { get; set; }
    }
}

Controllers/AveriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EsquemasSecundarios.Models;
using System.Data.SqlClient;
using System.Web.Configuration;

namespace EsquemasSecundarios.Controllers
{
    [TienePermiso(Servicio: 22)]// Servicio: Gestionar Averías
    public class AveriasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();       

        // GET: Averias
        [AllowAnonymous]
        public ActionResult Index()
        {            
            var averias = db.Averias.Include(c => c.Esquema);
            return View(averias);
        }

        // GET: Averias/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Averias averias = db.Averias.Find(id);
            if (averias == null)
            {
                return HttpNotFound();
            }
            ViewBag.NombreEsquema = db.EsquemasProteccion.Find(averias.IdEsquema).Nombre;
            var sub = db.Subestacion.Find(averias.CodSubestacion);
            var subtra = db.SubestacionTransmision.Find(averias.CodSubestacion);
            if (sub != null && subtra == null)
                ViewBag.NombreSubestacion = sub.NombreSubestacion;
            else if (sub == null && subtra != null)
                ViewBag.NombreSubestacion = subtra.NombreSubestacion;

            return View(averias);
        }

        // GET: Averias/Create
        public ActionResult Create()
        {
            var subestaciones = db.Subestacion
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion })
                .Union(db.SubestacionTransmision
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion }));

            ViewBag.CodSubestacion = new SelectList(subestaciones, "Value", "Text");
            ViewBag.IdEsquema = new SelectList(db.EsquemasProteccion, "id_Esquema", "Nombre");
            ViewBag.PersonaQueAtendio = new SelectList(db.Personal, "Nombre", "Nombre");
            ViewBag.ElaboradoPor = new SelectList(db.Personal, "Nombre", "Nombre");
            ViewBag.RevisadoPor = new SelectList(db.Personal, "Nombre", "Nombre");
            ViewBag.AprobadoPor = new SelectList(db.Personal, "Nombre", "Nombre");

            return View();
        }

        // POST: Averias/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdAveria,FechaReporte,CodSubestacion,IdEsquema,FechaAtencion,PersonaQueAtendio,DatosReportados,Analisis,Conclusiones,Recomendaciones,ElaboradoPor,RevisadoPor,AprobadoPor")] Averias averias,
            string CodSubestacion , int? IdEsquema, string PersonaQueAtendio, string ElaboradoPor, string RevisadoPor, string AprobadoPor)
        {
            var usuario = System.Web.HttpContext.Current.User?.Identity?.Name ?? null;
            string nombre_usuario = System.Web.HttpContext.Current.User.Identity.Name;
            var usuario_logueado = db.Personal.FirstOrDefault(c => c.Nombre == nombre_usuario);
            short EAdmin = usuario_logueado.id_EAdministrativa;

            int idesq = IdEsquema ?? -1;

            if (ModelState.IsValid && idesq != -1 && CodSubestacion != "")
            {
                averias.CodSubestacion = CodSubestacion;
                averias.IdEsquema = idesq;
                averias.PersonaQueAtendio = PersonaQueAtendio;
                averias.ElaboradoPor = ElaboradoPor;
                averias.RevisadoPor = RevisadoPor;
                averias.AprobadoPor = AprobadoPor;
                averias.Id_EAdministrativa = EAdmin;
                averias.Id_NumAccion = GetNumAccion("I", "ESA", 0);
                db.Averias.Add(averias);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = averias.IdAveria });
            }
            var subestaciones = db.Subestacion
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion })
                .Union(db.SubestacionTransmision
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion }));
            ViewBag.CodSubestacion = new SelectList(subestaciones, "Value", "Text", CodSubestacion);

            var e = db.EsquemasProteccion.Where(c => c.Subestacion == CodSubestacion);
            ViewBag.IdEsquema = new SelectList(e, "id_Esquema", "Nombre", IdEsquema);

            ViewBag.PersonaQueAtendio = new SelectList(db.Personal, "Nombre", "Nombre", PersonaQueAtendio);
            ViewBag.ElaboradoPor = new SelectList(db.Personal, "Nombre", "Nombre", ElaboradoPor);
            ViewBag.RevisadoPor = new SelectList(db.Personal, "Nombre", "Nombre", RevisadoPor);
            ViewBag.AprobadoPor = new SelectList(db.Personal, "Nombre", "Nombre", AprobadoPor);

            ViewBag.ErrorEsquema = "";
            if (idesq == -1)
            {
                ViewBag.ErrorEsquema = "Debe seleccionar un esquema";
            }

            return View(averias);
        }

        // GET: Averias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Averias averias = db.Averias.Find(id);
            if (averias == null)
            {
                return HttpNotFound();
            }
            var subestaciones = db.Subestacion
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion })
                .Union(db.SubestacionTransmision
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion }));
            ViewBag.CodSubestacion = new SelectList(subestaciones, "Value", "Text", averias.CodSubestacion);

            var e = db.EsquemasProteccion.Where(c => c.Subestacion == averias.CodSubestacion);
            ViewBag.IdEsquema = new SelectList(e, "id_Esquema", "Nombre", averias.IdEsquema);

            ViewBag.PersonaQueAtendio = new SelectList(db.Personal, "Nombre", "Nombre", averias.PersonaQueAtendio);
            ViewBag.ElaboradoPor = new SelectList(db.Personal, "Nombre", "Nombre", averias.ElaboradoPor);
            ViewBag.RevisadoPor = new SelectList(db.Personal, "Nombre", "Nombre", averias.RevisadoPor);
            ViewBag.AprobadoPor = new SelectList(db.Personal, "Nombre", "Nombre", averias.AprobadoPor);

            return View(averias);
        }

        // POST: Averias/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdAveria,FechaReporte,CodSubestacion,IdEsquema,FechaAtencion,PersonaQueAtendio,DatosReportados,Analisis,Conclusiones,Recomendaciones,ElaboradoPor,RevisadoPor,AprobadoPor")] Averias averias,
            string CodSubestacion, int? IdEsquema, string PersonaQueAtendio, string ElaboradoPor, string RevisadoPor, string AprobadoPor)
        {
            var usuario = System.Web.HttpContext.Current.User?.Identity?.Name ?? null;
            string nombre_usuario = System.Web.HttpContext.Current.User.Identity.Name;
            var usuario_logueado = db.Personal.FirstOrDefault(c => c.Nombre == nombre_usuario);
            short EAdmin = usuario_logueado.id_EAdministrativa;

            int idesq = IdEsquema ?? -1;

            if (ModelState.IsValid && idesq != -1 && CodSubestacion != "")
            {
                averias.CodSubestacion = CodSubestacion;
                averias.IdEsquema = idesq;
                averias.PersonaQueAtendio = PersonaQueAtendio;
                averias.ElaboradoPor = ElaboradoPor;
                averias.RevisadoPor = RevisadoPor;
                averias.AprobadoPor = AprobadoPor;
                averias.Id_EAdministrativa = EAdmin;
                averias.Id_NumAccion = GetNumAccion("M", "ESA", averias.Id_NumAccion ?? 0);
                db.Entry(averias).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Details", new { id = averias.IdAveria });
            }
            var subestaciones = db.Subestacion
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion })
                .Union(db.SubestacionTransmision
                .Select(c => new SelectListItem { Value = c.Codigo, Text = c.Codigo + " - " + c.NombreSubestacion }));
            ViewBag.CodSubestacion = new SelectList(subestaciones, "Value", "Text", CodSubestacion);

            var e = db.EsquemasProteccion.Where(c => c.Subestacion == CodSubestacion);
            ViewBag.IdEsquema = new SelectList(e, "id_Esquema", "Nombre", averias.IdEsquema);

            ViewBag.PersonaQueAtendio = new SelectList(db.Personal, "Nombre", "Nombre", averias.PersonaQueAtendio);
            ViewBag.ElaboradoPor = new SelectList(db.Personal, "Nombre", "Nombre", averias.ElaboradoPor);
            ViewBag.RevisadoPor = new SelectList(db.Personal, "Nombre", "Nombre", averias.RevisadoPor);
            ViewBag.AprobadoPor = new SelectList(db.Personal, "Nombre", "Nombre", averias.AprobadoPor);

            ViewBag.ErrorEsquema = "";
            if (idesq == -1)
            {
                ViewBag.ErrorEsquema = "Debe seleccionar un esquema";
            }

            return View(averias);
        }

        // GET: Averias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Averias averias = db.Averias.Find(id);

Views/Averias/Delete.cshtml
@model EsquemasSecundarios.Models.Averias

@{
    ViewBag.Title = "Averías";
}
<h3 class="alert alert-warning">&iexcl;Advertencia! - Esta acción es irreversible.</h3>
<!-- content starts here -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Eliminar avería</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- content starts here -->                
                <div>
                    <div class="row clearfix">
                        <div class="col-md-12">
                            <table class="table">
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.Subestacion)</th>
                                    <td>@Html.DisplayFor(model => model.CodSubestacion)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.Esquema)</th>
                                    <td>@ViewBag.Esquema</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.FechaReporte)</th>
                                    <td>@Html.DisplayFor(model => model.FechaReporte)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.FechaAtencion)</th>
                                    <td>@Html.DisplayFor(model => model.FechaAtencion)</td>
                                </tr>
                                <tr>
                                    <th> @Html.DisplayNameFor(model => model.PersonaQueAtendio)</th>
                                    <td>@Html.DisplayFor(model => model.PersonaQueAtendio)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.DatosReportados)</th>
                                    <td>@Html.DisplayFor(model => model.DatosReportados)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.Analisis)</th>
                                    <td>@Html.DisplayFor(model => model.Analisis)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.Conclusiones)</th>
                                    <td>@Html.DisplayFor(model => model.Conclusiones)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.Recomendaciones)</th>
                                    <td>@Html.DisplayFor(model => model.Recomendaciones)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.ElaboradoPor)</th>
                                    <td>@Html.DisplayFor(model => model.ElaboradoPor)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.RevisadoPor)</th>
                                    <td>@Html.DisplayFor(model => model.RevisadoPor)</td>
                                </tr>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.AprobadoPor)</th>
                                    <td>@Html.DisplayFor(model => model.AprobadoPor)</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <hr />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <button type="submit" class="btn btn-danger"><i class="fa fa-eraser"></i> Eliminar</button>
                            <a class="btn btn-default" href="@Url.Action("Index","Averias")"><i class="fa fa-list"></i> Listado</a>
                        </div>
                    }
                </div>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

Views/Averias/Details.cshtml
@model EsquemasSecundarios.Models.Averias

@{
    ViewBag.Title = "Averías";
}
<!-- content starts here -->
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Detalles de la Avería</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- content starts here -->
                <div class="row clearfix">
                    <div class="col-md-6">
                        <table class="table">
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Subestacion)</th>
                                <td>@Html.DisplayFor(model => model.CodSubestacion) - @ViewBag.NombreSubestacion</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Esquema)</th>
                                <td>@ViewBag.NombreEsquema</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.FechaReporte)</th>
                                <td>@Html.DisplayFor(model => model.FechaReporte)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.FechaAtencion)</th>
                                <td>@Html.DisplayFor(model => model.FechaAtencion)</td>
                            </tr>
                            <tr>
                                <th> @Html.DisplayNameFor(model => model.PersonaQueAtendio)</th>
                                <td>@Html.DisplayFor(model => model.PersonaQueAtendio)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.ElaboradoPor)</th>
                                <td>@Html.DisplayFor(model => model.ElaboradoPor)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.RevisadoPor)</th>
                                <td>@Html.DisplayFor(model => model.RevisadoPor)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.AprobadoPor)</th>
                                <td>@Html.DisplayFor(model => model.AprobadoPor)</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-6">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <b>@Html.DisplayNameFor(model => model.DatosReportados)</b>
                                <p>@Html.DisplayFor(model => model.DatosReportados)</p>

                                <b>@Html.DisplayNameFor(model => model.Analisis)</b>
                                <p>@Html.DisplayFor(model => model.Analisis)</p>

                                <b>@Html.DisplayNameFor(model => model.Conclusiones)</b>
                                <p>@Html.DisplayFor(model => model.Conclusiones)</p>

                                <b>@Html.DisplayNameFor(model => model.Recomendaciones)</b>
                                <p>@Html.DisplayFor(model => model.Recomendaciones)</p>
                            </div>
                        </div>
                    </div>
                </div>
                <hr />
                <p>
                    <a class="btn btn-success" href="@Url.Action("Create","Averias")"><i class="fa fa-plus"></i> Nueva</a>
                    <a class="btn btn-warning" href="@Url.Action("Edit","Averias", new { id = Model.IdAveria })"><i class="fa fa-edit"></i> Editar</a>
                    <a class="btn btn-default" href="@Url.Action("Index","Averias")"><i class="fa fa-list"></i> Listado</a>
                </p>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

Views/Averias/Index.cshtml
@model IEnumerable<EsquemasSecundarios.Models.Averias>

@{
    ViewBag.Title = "Averías";
}

<!-- content starts here -->

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Listado de averías</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-question"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- content starts here -->
                <div class="row">
                    <div class="col-md-12">
                        <table id="datatable" class="table table-striped table-bordered table-hover table-responsive">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.FechaReporte)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Subestacion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Esquema)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.FechaAtencion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PersonaQueAtendio)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ElaboradoPor)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.RevisadoPor)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.AprobadoPor)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.DatosReportados)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Analisis)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Conclusiones)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Recomendaciones)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FechaReporte)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CodSubestacion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Esquema.Nombre)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FechaAtencion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PersonaQueAtendio)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ElaboradoPor)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.RevisadoPor)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AprobadoPor)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DatosReportados)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Analisis)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Conclusiones)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Recomendaciones)
                                        </td>
                                        <td style="width: 95px;">
                                            <a href="@Url.Action("Details","Averias", new { id = item.IdAveria } )" class="btn btn-info btn-xs" title="Detalles"><i class="fa fa-eye"></i>  </a>
                                            <a href="@Url.Action("Edit","Averias", new { id = item.IdAveria } )" class="btn btn-warning btn-xs" title="Editar"><i class="fa fa-pencil"></i>  </a>
                                            <a href="@Url.Action("Delete","Averias", new { id = item.IdAveria } )" class="btn btn-danger btn-xs" title="Eliminar"><i class="fa fa-trash-o"></i>  </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-12">
                        <a href="@Url.Action("Create","Averias")" class="btn btn-info"><i class="fa fa-plus"></i> Nueva</a>
                    </div>
                </div>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

@section styles {
    @Styles.Render("~/Style/DataTables")
}

@section script {
    @Scripts.Render("~/Script/DataTables")
}

Views/Averias/_CargarEsquemas.cshtml
@Html.DropDownList("IdEsquema", null, "", htmlAttributes: new { @class = "select2_single form-control" })